### ISSUE TITLE
(Feature Request) Select menu at song wheel scrolls when there are too many options

### ISSUE THREAD

**Issue by dude98** [DarkBahamut162/itg3encore#2]
currently it just keeps displaying options outside of the menu, going off screen. it'd look nicer and be easier to use if it scrolled, and possibly was a single column rather than two columns? especially since left/right don't do anything for the select menu, when the arrows that show up point left and right.
i'm using the five button menu mode, if three button makes left and right work.

**Comment by DarkBahamut162** [comment]
First of all: I can't make it scroll myself as it's an engine issue.
Second of all: I was literally asking for this on an issue over at [Project OutFox](https://github.com/TeamRizu/OutFox/issues/398) but nothing happened as of now with that.

I know that there are themes out there that can do that. But, from when I last checked, those are lua lists made from scratch, which this isn't and I'm unable to do currently.

Also, it currently only has the default controls: up & down. I'm not sure if I could make it left/up & down/right. But that would be the only thing I could do.

**Comment by DarkBahamut162** [comment]
I managed to clean it up a bit more, but certain menues (like noteskins) might still be stuck having potentially too many options depending on how many had been selected on install (since they pull those from global as well as the ones for the current game mode).
