### ISSUE TITLE
Can't input any buttons in name entry screen (USB profile inserted, home mode)

### ISSUE THREAD

**Issue by dude98** [DarkBahamut162/itg3encore#4]
after playing in normal mode (not event) and getting to the high score entry screen, i couldn't do anything, hitting start didn't input a letter, left and right wouldn't move the panel, and not even hitting back did anything.
i use an 11 character name on my USB profile that it auto entered, but i also had to wait for the timer to run out since no inputs worked.
idk if it's a glitch from too long of a user, because of usb profiles, or just a glitch for the screen itself.

**Comment by DarkBahamut162** [comment]
This is a known issue as I came across this yesterday myself but couldn't fix it yet.
My only question would be: Had it actually worked before?

**Comment by DarkBahamut162** [comment]
I've added a potential fix. Not sure if it's working fully but it worked the last time I checked.

**Comment by DarkBahamut162** [comment]
No responce to the fix has been made.
It's assumed that the fix worked.
If not, please reopen the issue.
